apiVersion: config.istio.io/v1alpha2
kind: RouteRule
metadata:
  name: provider-canary
spec:
  destination:
    name: provider-svc
  precedence: 2
  route:
  - labels:
      version: v1
    weight: 90
  - labels:
      version: v2
    weight: 10
